"""Simple spell checker for screenplay text with Fountain-aware word skipping."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

_COMMON_WORDS = frozenset({
    "a", "ab", "abandon", "abandoned", "abbey", "ability", "able", "aboard",
    "abolish", "about", "above", "abroad", "absence", "absent", "absolute",
    "absolutely", "absorb", "absorbed", "abstract", "absurd", "abundance",
    "abuse", "academy", "accelerate", "accent", "accept", "acceptable",
    "acceptance", "accepted", "access", "accessible", "accident", "accidental",
    "accidentally", "accommodate", "accompany", "accomplish", "accomplished",
    "accomplishment", "accord", "accordance", "according", "accordingly",
    "account", "accountant", "accounting", "accumulate", "accuracy", "accurate",
    "accurately", "accusation", "accuse", "accused", "accustomed", "ace",
    "ache", "achieve", "achievement", "acid", "acknowledge", "acquaintance",
    "acquire", "acquisition", "acre", "across", "act", "action", "activate",
    "active", "actively", "activist", "activity", "actor", "actress", "actual",
    "actually", "acute", "ad", "adam", "adapt", "adaptation", "add", "added",
    "addiction", "addition", "additional", "additionally", "address", "adequate",
    "adequately", "adjust", "adjustment", "administration", "administrator",
    "admirable", "admiral", "admiration", "admire", "admission", "admit",
    "adolescent", "adopt", "adoption", "adult", "advance", "advanced",
    "advancement", "advantage", "adventure", "adventurous", "adversary",
    "adverse", "advertise", "advertisement", "advice", "advise", "adviser",
    "advisor", "advisory", "advocate", "aerial", "affair", "affect",
    "affection", "affectionate", "affirm", "afford", "affordable", "afraid",
    "after", "afternoon", "afterward", "afterwards", "again", "against", "age",
    "aged", "agency", "agenda", "agent", "aggression", "aggressive", "agile",
    "aging", "agitate", "ago", "agony", "agree", "agreeable", "agreed",
    "agreement", "agricultural", "agriculture", "ahead", "aid", "aide", "aim",
    "air", "aircraft", "airline", "airplane", "airport", "aisle", "alarm",
    "alarmed", "alarming", "album", "alcohol", "alcoholic", "ale", "alert",
    "alien", "alienate", "align", "alike", "alive", "all", "allegation",
    "allege", "alleged", "allegedly", "allegiance", "allergic", "allergy",
    "alley", "alliance", "allied", "allocate", "allocation", "allow",
    "allowance", "ally", "almost", "alone", "along", "alongside", "aloud",
    "alphabet", "alphabetical", "alpine", "already", "also", "altar", "alter",
    "alternate", "alternative", "alternatively", "although", "altitude",
    "altogether", "aluminum", "aluminium", "always", "amateur", "amaze",
    "amazed", "amazing", "amazingly", "ambassador", "amber", "ambiguity",
    "ambiguous", "ambition", "ambitious", "ambulance", "amend", "amendment",
    "amid", "among", "amongst", "amount", "ample", "amuse", "amused",
    "amusement", "amusing", "an", "analyse", "analysis", "analyst",
    "analytical", "analyze", "ancestor", "ancient", "and", "angel", "anger",
    "angle", "angry", "animal", "ankle", "anniversary", "announce",
    "announcement", "annoy", "annoyance", "annoyed", "annoying", "annual",
    "annually", "anonymous", "another", "answer", "ant", "anticipate",
    "anticipation", "anxiety", "anxious", "anxiously", "any", "anybody",
    "anyhow", "anymore", "anyone", "anything", "anyway", "anywhere", "apart",
    "apartment", "apathy", "ape", "apology", "apologize", "apostle", "app",
    "apparatus", "apparel", "apparent", "apparently", "appeal", "appealing",
    "appear", "appearance", "appetite", "apple", "applicable", "applicant",
    "application", "apply", "appoint", "appointed", "appointment", "appraisal",
    "appreciate", "appreciation", "approach", "appropriate", "appropriately",
    "approval", "approve", "approximate", "approximately", "april", "apron",
    "apt", "aquarium", "arbitrary", "arc", "arch", "architect", "architectural",
    "architecture", "archive", "arctic", "ardent", "are", "area", "arena",
    "arguably", "argue", "argument", "arise", "aristocrat", "arm", "armed",
    "armor", "armour", "army", "aroma", "around", "arouse", "arrange",
    "arrangement", "array", "arrest", "arrival", "arrive", "arrogance",
    "arrogant", "arrow", "art", "article", "articulate", "artificial",
    "artist", "artistic", "artwork", "as", "ash", "ashamed", "ashore", "aside",
    "ask", "asleep", "aspect", "aspiration", "aspire", "assault", "assemble",
    "assembly", "assert", "assertion", "assess", "assessment", "asset",
    "assign", "assignment", "assist", "assistance", "assistant", "associate",
    "associated", "association", "assume", "assumption", "assurance", "assure",
    "assured", "asteroid", "astonish", "astonishing", "astronaut", "astronomy",
    "asylum", "at", "ate", "athlete", "athletic", "athletics", "atmosphere",
    "atmospheric", "atom", "atomic", "atop", "attach", "attached", "attachment",
    "attack", "attacker", "attain", "attempt", "attend", "attendance",
    "attendant", "attention", "attic", "attitude", "attorney", "attract",
    "attraction", "attractive", "attribute", "auction", "audible", "audience",
    "audio", "audit", "audition", "august", "aunt", "authentic", "author",
    "authoritative", "authority", "auto", "automatic", "automatically",
    "automobile", "autumn", "availability", "available", "avenue", "average",
    "avid", "avoid", "await", "awake", "awaken", "award", "aware", "awareness",
    "away", "awe", "awesome", "awful", "awfully", "awhile", "awkward",
    "awkwardly", "axis",
    "baby", "bachelor", "back", "backbone", "backdrop", "background",
    "backing", "backpack", "backstage", "backup", "backward", "backwards",
    "backyard", "bacon", "bacteria", "bad", "badge", "badly", "bag", "bail",
    "bait", "bake", "baker", "bakery", "balance", "balanced", "balcony",
    "bald", "ball", "ballet", "balloon", "ballot", "ban", "banana", "band",
    "bandage", "bang", "bank", "banker", "banking", "bankruptcy", "banner",
    "bar", "bare", "barely", "bargain", "barn", "barrel", "barrier", "base",
    "baseball", "based", "baseline", "basement", "basic", "basically", "basics",
    "basin", "basis", "basket", "basketball", "bass", "bastard", "bat",
    "batch", "bath", "bathroom", "battery", "battle", "battlefield", "bay",
    "be", "beach", "beacon", "bead", "beam", "bean", "bear", "beard",
    "bearing", "beast", "beat", "beaten", "beating", "beautiful",
    "beautifully", "beauty", "because", "become", "bed", "bedroom", "bee",
    "beef", "been", "beer", "before", "beforehand", "beg", "began", "begin",
    "beginner", "beginning", "begun", "behalf", "behave", "behavior",
    "behaviour", "behind", "being", "belief", "believe", "believer", "bell",
    "belly", "belong", "belonging", "belongings", "beloved", "below", "belt",
    "bench", "bend", "beneath", "beneficial", "benefit", "bent", "berry",
    "beside", "besides", "best", "bet", "betray", "betrayal", "better",
    "between", "beyond", "bias", "bible", "biblical", "bicycle", "bid", "big",
    "bigger", "biggest", "bike", "bill", "billion", "bin", "bind", "binding",
    "biography", "biological", "biology", "bird", "birth", "birthday",
    "biscuit", "bishop", "bit", "bite", "bitter", "bitterly", "bizarre",
    "black", "blade", "blame", "bland", "blank", "blanket", "blast", "blaze",
    "bleak", "bleed", "bleeding", "blend", "bless", "blessed", "blessing",
    "blind", "blink", "bliss", "blister", "block", "blonde", "blood", "bloody",
    "bloom", "blossom", "blow", "blown", "blue", "blueprint", "blues", "bluff",
    "blur", "blurt", "blush", "board", "boast", "boat", "bob", "body",
    "bodyguard", "boil", "bold", "bolt", "bomb", "bomber", "bombing", "bond",
    "bone", "bonus", "book", "booking", "booklet", "boom", "boost", "boot",
    "booth", "border", "bore", "bored", "boredom", "boring", "born", "borrow",
    "boss", "both", "bother", "bottle", "bottom", "boulder", "boulevard",
    "bounce", "bound", "boundary", "bouquet", "bout", "bow", "bowl", "box",
    "boy", "boyfriend", "brace", "bracelet", "bracket", "brain", "brake",
    "branch", "brand", "brave", "bravery", "breach", "bread", "break",
    "breakdown", "breakfast", "breakthrough", "breast", "breath", "breathe",
    "breathing", "breathless", "breathtaking", "breed", "breeding", "breeze",
    "brew", "brewery", "brick", "bride", "bridge", "brief", "briefcase",
    "briefing", "briefly", "brigade", "bright", "brighten", "brightly",
    "brightness", "brilliant", "brim", "bring", "brink", "brisk", "broad",
    "broadcast", "broadcaster", "broadly", "brochure", "broke", "broken",
    "bronze", "brook", "brother", "brown", "browse", "browser", "bruise",
    "brush", "brutal", "brutality", "bubble", "buck", "bucket", "bud",
    "buddy", "budget", "bug", "build", "builder", "building", "bulk", "bull",
    "bullet", "bulletin", "bully", "bump", "bunch", "bundle", "burden",
    "bureau", "bureaucracy", "bureaucratic", "burger", "burial", "burn",
    "burning", "burst", "bury", "bus", "bush", "business", "businessman",
    "busy", "but", "butcher", "butter", "butterfly", "button", "buy", "buyer",
    "buzz", "by", "bye",
    "cab", "cabin", "cabinet", "cable", "cafe", "cage", "cake", "calculate",
    "calculation", "calendar", "call", "caller", "calm", "calmly", "came",
    "camera", "camp", "campaign", "campus", "can", "canal", "cancel",
    "cancellation", "cancer", "candidate", "candle", "candy", "canvas", "cap",
    "capability", "capable", "capacity", "cape", "capital", "capitalism",
    "capitalist", "captain", "caption", "capture", "car", "carbon", "card",
    "care", "career", "careful", "carefully", "careless", "cargo", "carnival",
    "carpet", "carriage", "carrier", "carrot", "carry", "cart", "carve",
    "case", "cash", "casino", "cast", "castle", "casual", "casually",
    "casualty", "cat", "catalog", "catalogue", "catch", "category", "cater",
    "cathedral", "cattle", "caught", "cause", "caution", "cautious",
    "cautiously", "cave", "cease", "ceiling", "celebrate", "celebration",
    "celebrity", "cell", "cellar", "cement", "cemetery", "census", "cent",
    "center", "central", "centre", "century", "ceremony", "certain",
    "certainly", "certainty", "certificate", "chain", "chair", "chairman",
    "chairwoman", "challenge", "challenger", "challenging", "chamber",
    "champion", "championship", "chance", "chancellor", "change", "channel",
    "chaos", "chaotic", "chap", "chapel", "chapter", "character",
    "characteristic", "characterize", "charge", "charity", "charm", "charming",
    "chart", "charter", "chase", "chat", "cheap", "cheat", "check", "cheek",
    "cheer", "cheerful", "cheese", "chef", "chemical", "chemistry", "chest",
    "chew", "chicken", "chief", "child", "childhood", "children", "chill",
    "chilly", "chimney", "chin", "chip", "chocolate", "choice", "choir",
    "choke", "choose", "chop", "chord", "chore", "chorus", "chose", "chosen",
    "chronic", "chronicle", "chunk", "church", "cigarette", "cinema",
    "circle", "circuit", "circular", "circulate", "circulation", "circumstance",
    "cite", "citizen", "citizenship", "city", "civic", "civil", "civilian",
    "civilization", "claim", "clap", "clarify", "clarity", "clash", "clasp",
    "class", "classic", "classical", "classification", "classify", "classmate",
    "classroom", "clause", "claw", "clay", "clean", "cleaner", "cleaning",
    "clear", "clearance", "clearing", "clearly", "clerk", "clever", "click",
    "client", "cliff", "climate", "climb", "climber", "cling", "clinic",
    "clinical", "clip", "cloak", "clock", "clone", "close", "closed",
    "closely", "closer", "closest", "closet", "closing", "closure", "cloth",
    "clothe", "clothes", "clothing", "cloud", "cloudy", "club", "clue",
    "cluster", "clutch", "clutter", "coach", "coaching", "coal", "coalition",
    "coast", "coastal", "coat", "cocktail", "code", "coffee", "coffin",
    "cognitive", "coherent", "coin", "coincide", "coincidence", "cold",
    "collaborate", "collaboration", "collaborative", "collapse", "collar",
    "colleague", "collect", "collection", "collective", "collector", "college",
    "colonial", "colony", "color", "colour", "coloured", "colorful",
    "colourful", "column", "columnist", "combat", "combination", "combine",
    "come", "comeback", "comedy", "comfort", "comfortable", "comfortably",
    "comic", "coming", "command", "commander", "commence", "comment",
    "commentary", "commentator", "commerce", "commercial", "commission",
    "commissioner", "commit", "commitment", "committee", "commodity", "common",
    "commonly", "commonwealth", "communicate", "communication", "communist",
    "community", "companion", "company", "comparable", "comparative",
    "compare", "comparison", "compel", "compelling", "compensate",
    "compensation", "compete", "competence", "competent", "competing",
    "competition", "competitive", "competitor", "complain", "complaint",
    "complement", "complete", "completely", "completion", "complex",
    "complexity", "compliance", "complicate", "complicated", "complication",
    "compliment", "comply", "component", "compose", "composer", "composition",
    "compound", "comprehensive", "comprise", "compromise", "compulsory",
    "compute", "computer", "computing", "conceal", "concede", "conceive",
    "concentrate", "concentration", "concept", "concern", "concerned",
    "concerning", "concert", "conclude", "conclusion", "concrete", "condemn",
    "condition", "conduct", "conductor", "cone", "conference", "confess",
    "confession", "confidence", "confident", "confidential", "confine",
    "confirm", "confirmation", "conflict", "conform", "confront",
    "confrontation", "confuse", "confused", "confusing", "confusion",
    "congratulate", "congregation", "congress", "congressional", "connect",
    "connected", "connection", "conscience", "conscious", "consciousness",
    "consensus", "consent", "consequence", "consequently", "conservation",
    "conservative", "consider", "considerable", "considerably", "consideration",
    "consist", "consistency", "consistent", "consistently", "conspiracy",
    "constant", "constantly", "constituency", "constitute", "constitution",
    "constitutional", "construct", "construction", "consultant",
    "consultation", "consume", "consumer", "consumption", "contact", "contain",
    "container", "contemporary", "contempt", "contend", "content", "contest",
    "contestant", "context", "continent", "continental", "continually",
    "continue", "continued", "continuous", "continuously", "contract",
    "contractor", "contradiction", "contrary", "contrast", "contribute",
    "contribution", "contributor", "control", "controller", "controversial",
    "controversy", "convenience", "convenient", "convention", "conventional",
    "conversation", "conversion", "convert", "conviction", "convince",
    "convinced", "convincing", "cook", "cookie", "cooking", "cool", "cope",
    "copper", "copy", "coral", "cord", "core", "corn", "corner", "corporate",
    "corporation", "correct", "correction", "correctly", "correlation",
    "correspond", "correspondence", "correspondent", "corresponding",
    "corridor", "corrupt", "corruption", "cost", "costly", "costume",
    "cottage", "cotton", "couch", "could", "council", "counsel", "counselor",
    "counsellor", "count", "counter", "counterpart", "countless", "country",
    "countryside", "county", "coup", "couple", "courage", "courageous",
    "course", "court", "courtesy", "courtroom", "courtyard", "cousin", "cover",
    "coverage", "cow", "coward", "crack", "craft", "crash", "crawl", "crazy",
    "cream", "create", "creation", "creative", "creativity", "creator",
    "creature", "credential", "credibility", "credible", "credit", "crew",
    "cricket", "crime", "criminal", "crisis", "crisp", "criteria", "criterion",
    "critic", "critical", "critically", "criticism", "criticize", "critique",
    "crop", "cross", "crossing", "crouch", "crowd", "crowded", "crown",
    "crucial", "cruel", "cruelty", "cruise", "crush", "cry", "crystal", "cue",
    "cult", "cultural", "culture", "cup", "cupboard", "cure", "curiosity",
    "curious", "curiously", "curl", "currency", "current", "currently",
    "curriculum", "curse", "curtain", "curve", "custody", "custom", "customer",
    "customs", "cut", "cute", "cutting", "cycle", "cyclist",
    "dad", "daddy", "daily", "dairy", "dam", "damage", "damn", "damp",
    "dance", "dancer", "dancing", "danger", "dangerous", "dangerously", "dare",
    "daring", "dark", "darken", "darkness", "darling", "dash", "data",
    "database", "date", "daughter", "dawn", "day", "daylight", "dead",
    "deadline", "deadly", "deaf", "deal", "dealer", "dealing", "dear",
    "dearly", "death", "debate", "debris", "debt", "debut", "decade", "decay",
    "decent", "decently", "decide", "decision", "decisive", "deck",
    "declaration", "declare", "decline", "decorate", "decoration", "decrease",
    "decree", "dedicate", "dedicated", "dedication", "deem", "deep", "deepen",
    "deeply", "deer", "default", "defeat", "defect", "defence", "defend",
    "defendant", "defender", "defense", "defensive", "defiance", "defiant",
    "deficiency", "deficit", "define", "definite", "definitely", "definition",
    "defy", "degree", "delay", "delegate", "delegation", "deliberate",
    "deliberately", "delicate", "delicious", "delight", "delighted",
    "delightful", "deliver", "delivery", "demand", "demanding", "democracy",
    "democrat", "democratic", "demolish", "demonstrate", "demonstration",
    "denial", "denounce", "dense", "density", "deny", "depart", "department",
    "departure", "depend", "dependence", "dependent", "depict", "deploy",
    "deployment", "deposit", "depression", "deprive", "deputy", "derive",
    "descend", "descent", "describe", "description", "desert", "deserve",
    "design", "designate", "designer", "desirable", "desire", "desk",
    "despair", "desperate", "desperately", "desperation", "despite", "dessert",
    "destination", "destiny", "destroy", "destruction", "destructive",
    "detail", "detailed", "detain", "detect", "detection", "detective",
    "detector", "determination", "determine", "determined", "devastating",
    "develop", "developer", "developing", "development", "device", "devil",
    "devise", "devote", "devoted", "devotion", "dialogue", "diamond", "diary",
    "dictate", "dictator", "dictionary", "did", "die", "diesel", "diet",
    "differ", "difference", "different", "differently", "difficult",
    "difficulty", "dig", "digest", "digital", "dignity", "dilemma",
    "dimension", "diminish", "dine", "dining", "dinner", "diplomat",
    "diplomatic", "dire", "direct", "direction", "directly", "director",
    "directory", "dirt", "dirty", "disability", "disabled", "disadvantage",
    "disagree", "disagreement", "disappear", "disappearance", "disappoint",
    "disappointed", "disappointing", "disappointment", "disapproval",
    "disapprove", "disaster", "disastrous", "discipline", "disclose",
    "disclosure", "disco", "discount", "discourse", "discover", "discovery",
    "discretion", "discrimination", "discuss", "discussion", "disease",
    "disgrace", "disguise", "disgust", "dish", "dismiss", "dismissal",
    "disorder", "dispatch", "displace", "display", "disposal", "dispose",
    "disposition", "dispute", "dissolve", "distance", "distant", "distinct",
    "distinction", "distinctive", "distinguish", "distinguished", "distort",
    "distract", "distraction", "distress", "distribute", "distribution",
    "district", "disturb", "disturbance", "disturbing", "ditch", "dive",
    "diverse", "diversity", "divide", "divine", "division", "divorce", "do",
    "dock", "doctor", "doctrine", "document", "documentary", "documentation",
    "dodge", "does", "dog", "dollar", "domain", "dome", "domestic", "dominant",
    "dominate", "donation", "done", "donor", "doom", "door", "doorstep",
    "doorway", "dose", "dot", "double", "doubt", "doubtful", "doubtless",
    "dough", "down", "download", "downstairs", "downtown", "downward",
    "downwards", "dozen", "draft", "drag", "dragon", "drain", "drama",
    "dramatic", "dramatically", "drank", "drape", "draw", "drawer", "drawing",
    "drawn", "dread", "dream", "dress", "dressed", "drift", "drill", "drink",
    "drinking", "drip", "drive", "driven", "driver", "driving", "drop",
    "drought", "drove", "drown", "drug", "drum", "drummer", "drunk", "dry",
    "dual", "dub", "duck", "due", "dull", "dumb", "dump", "dune", "duration",
    "during", "dusk", "dust", "dusty", "duty", "dwelling", "dynamic",
    "dynasty",
    "each", "eager", "eagerly", "eagle", "ear", "earl", "earlier", "earliest",
    "early", "earn", "earnest", "earning", "earnings", "earth", "ease",
    "easily", "east", "eastern", "easy", "eat", "eaten", "echo", "economic",
    "economically", "economics", "economist", "economy", "ecosystem", "edge",
    "edit", "edition", "editor", "editorial", "educate", "educated",
    "education", "educational", "educator", "effect", "effective",
    "effectively", "effectiveness", "efficiency", "efficient", "efficiently",
    "effort", "egg", "ego", "eight", "eighteen", "eighteenth", "eighth",
    "eighty", "either", "elaborate", "elder", "elderly", "elect", "election",
    "electric", "electrical", "electricity", "electron", "electronic",
    "electronics", "elegant", "element", "elementary", "elephant", "elevate",
    "elevation", "elevator", "eleven", "eleventh", "eligible", "eliminate",
    "elimination", "elite", "else", "elsewhere", "embrace", "emerge",
    "emergence", "emergency", "emerging", "emission", "emotion", "emotional",
    "emotionally", "emperor", "emphasis", "emphasize", "empire", "employ",
    "employed", "employee", "employer", "employment", "empower", "empress",
    "empty", "enable", "enact", "encounter", "encourage", "encouragement",
    "encouraging", "end", "endless", "endorse", "endorsement", "endure",
    "enemy", "energetic", "energy", "enforce", "enforcement", "engage",
    "engaged", "engagement", "engine", "engineer", "engineering", "enhance",
    "enjoy", "enjoyable", "enjoyment", "enormous", "enormously", "enough",
    "enrich", "enroll", "enrollment", "ensure", "enter", "enterprise",
    "entertain", "entertainer", "entertaining", "entertainment", "enthusiasm",
    "enthusiast", "enthusiastic", "entire", "entirely", "entitle", "entitled",
    "entity", "entrance", "entrepreneur", "entry", "envelope", "environment",
    "environmental", "environmentalist", "envy", "epic", "epidemic", "episode",
    "equal", "equality", "equally", "equation", "equip", "equipment",
    "equivalent", "era", "erase", "erect", "erosion", "error", "erupt",
    "escalate", "escape", "escort", "especially", "essay", "essence",
    "essential", "essentially", "establish", "established", "establishment",
    "estate", "esteem", "estimate", "eternal", "ethics", "ethnic", "european",
    "evacuate", "evaluate", "evaluation", "eve", "even", "evening", "evenly",
    "event", "eventually", "ever", "every", "everybody", "everyday",
    "everyone", "everything", "everywhere", "evidence", "evident", "evidently",
    "evil", "evolution", "evolve", "exact", "exactly", "exaggerate",
    "exaggeration", "exam", "examination", "examine", "example", "exceed",
    "excellent", "except", "exception", "exceptional", "excess", "excessive",
    "exchange", "excitement", "exciting", "exclaim", "exclude", "exclusion",
    "exclusive", "exclusively", "excuse", "execute", "execution", "executive",
    "exempt", "exemption", "exercise", "exert", "exhaust", "exhausted",
    "exhaustion", "exhibit", "exhibition", "exile", "exist", "existence",
    "existing", "exit", "exotic", "expand", "expansion", "expect",
    "expectation", "expedition", "expenditure", "expense", "expensive",
    "experience", "experienced", "experiment", "experimental", "expert",
    "expertise", "explain", "explanation", "explicit", "explicitly", "explode",
    "exploit", "exploitation", "exploration", "explore", "explorer",
    "explosion", "explosive", "export", "expose", "exposed", "exposure",
    "express", "expression", "extend", "extended", "extension", "extensive",
    "extensively", "extent", "exterior", "external", "extra", "extract",
    "extraordinary", "extreme", "extremely", "eye", "eyebrow", "eyelid",
    "eyesight", "eyewitness",
    "fabric", "fabulous", "face", "facilitate", "facility", "fact", "faction",
    "factor", "factory", "faculty", "fade", "fail", "failing", "failure",
    "faint", "fair", "fairly", "fairy", "faith", "faithful", "fake", "fall",
    "fallen", "false", "fame", "familiar", "familiarity", "family", "famine",
    "famous", "fan", "fancy", "fantastic", "fantasy", "far", "fare",
    "farewell", "farm", "farmer", "farming", "fascinating", "fascination",
    "fashion", "fashionable", "fast", "fasten", "fat", "fatal", "fate",
    "father", "fault", "fauna", "favor", "favour", "favorable", "favourable",
    "favorite", "favourite", "fear", "feast", "feat", "feather", "feature",
    "february", "federal", "federation", "fee", "feeble", "feed", "feedback",
    "feel", "feeling", "fell", "fellow", "fellowship", "felt", "female",
    "feminine", "fence", "ferry", "fertile", "fertility", "festival", "fetch",
    "fever", "few", "fewer", "fibre", "fiber", "fiction", "fictional", "field",
    "fierce", "fiercely", "fifteen", "fifteenth", "fifth", "fifty", "fig",
    "fight", "fighter", "fighting", "figure", "file", "fill", "filled",
    "filling", "film", "filmmaker", "filter", "final", "finale", "finalist",
    "finally", "finance", "financial", "financially", "find", "finding",
    "fine", "finger", "fingertip", "finish", "finished", "fire", "fireplace",
    "firm", "firmly", "first", "fiscal", "fish", "fisher", "fisherman",
    "fishing", "fist", "fit", "fitness", "fitted", "fitting", "five", "fix",
    "fixed", "fixture", "flag", "flame", "flank", "flap", "flash", "flat",
    "flavor", "flavour", "flaw", "flawed", "flee", "fleet", "flesh",
    "flexibility", "flexible", "flicker", "flight", "fling", "flip", "float",
    "flock", "flood", "flooding", "floor", "flop", "flora", "flour",
    "flourish", "flow", "flower", "flu", "fluctuation", "fluent", "fluid",
    "flush", "fly", "flying", "foam", "focal", "focus", "focused", "fog",
    "fold", "folk", "follow", "follower", "following", "fond", "food",
    "fool", "foolish", "foot", "footage", "football", "footprint", "footstep",
    "for", "forbid", "forbidden", "force", "forecast", "forehead", "foreign",
    "foreigner", "forest", "forestry", "forever", "forget", "forgive",
    "forgiveness", "forgotten", "fork", "form", "formal", "formally",
    "format", "formation", "former", "formerly", "formula", "formulate",
    "forth", "forthcoming", "fortunate", "fortunately", "fortune", "forty",
    "forum", "forward", "fossil", "foster", "found", "foundation", "founder",
    "fountain", "four", "fourteen", "fourteenth", "fourth", "fraction",
    "fragile", "fragment", "frame", "framework", "franchise", "frank",
    "frankly", "fraud", "free", "freedom", "freely", "freeze", "freezing",
    "freight", "french", "frequency", "frequent", "frequently", "fresh",
    "friction", "friday", "friend", "friendly", "friendship", "fright",
    "frighten", "frightened", "frightening", "fringe", "from", "front",
    "frontier", "frost", "frozen", "fruit", "frustrate", "frustrated",
    "frustrating", "frustration", "fuel", "fulfil", "fulfill", "full",
    "fully", "fun", "function", "functional", "fund", "fundamental",
    "fundamentally", "funding", "funeral", "funny", "fur", "furious",
    "furiously", "furniture", "further", "furthermore", "fury", "fuss",
    "futile", "future",
    "gain", "galaxy", "gale", "gallery", "gallon", "game", "gang", "gap",
    "garage", "garbage", "garden", "gardener", "garlic", "garment", "gas",
    "gasoline", "gasp", "gate", "gateway", "gather", "gathering", "gauge",
    "gave", "gay", "gaze", "gear", "gender", "gene", "general", "generally",
    "generate", "generation", "generic", "generous", "generously", "genetic",
    "genius", "genre", "gentle", "gentleman", "gently", "genuine",
    "genuinely", "geographic", "geographical", "geography", "gesture", "get",
    "ghost", "giant", "gift", "gifted", "gig", "gigantic", "giggle", "girl",
    "girlfriend", "give", "given", "glad", "gladly", "glamour", "glance",
    "glare", "glass", "glasses", "gleam", "glimpse", "glitter", "global",
    "globally", "globe", "gloom", "gloomy", "glorious", "glory", "gloss",
    "glove", "glow", "glue", "go", "goal", "goat", "god", "goddess", "gold",
    "golden", "golf", "gone", "good", "goodbye", "goodness", "goods",
    "gorgeous", "gospel", "gossip", "got", "gotten", "govern", "governance",
    "government", "governor", "grab", "grace", "graceful", "gracious", "grade",
    "gradual", "gradually", "graduate", "graduation", "grain", "grammar",
    "grand", "grandchild", "granddaughter", "grandfather", "grandmother",
    "grandparent", "grandson", "granite", "grant", "grape", "graph",
    "graphic", "grasp", "grass", "grateful", "grave", "gravity", "gray",
    "graze", "grease", "great", "greatly", "greed", "greedy", "green",
    "greenhouse", "greet", "greeting", "grew", "grey", "grief", "grill",
    "grim", "grin", "grind", "grip", "groan", "grocery", "groom", "groove",
    "gross", "ground", "group", "grove", "grow", "growing", "grown", "growth",
    "guarantee", "guard", "guardian", "guerrilla", "guess", "guest",
    "guidance", "guide", "guideline", "guild", "guilt", "guilty", "guitar",
    "gulf", "gun", "gunfire", "gut", "guy", "gym",
    "habit", "habitat", "hack", "had", "hair", "hairy", "half", "halfway",
    "hall", "hallway", "halt", "ham", "hammer", "hand", "handful", "handle",
    "handsome", "handy", "hang", "hanging", "happen", "happening", "happily",
    "happiness", "happy", "harbor", "harbour", "hard", "harden", "hardly",
    "hardship", "hardware", "harm", "harmful", "harmony", "harness", "harsh",
    "harshly", "harvest", "has", "haste", "hastily", "hat", "hate", "hatred",
    "haul", "haunt", "haunting", "have", "haven", "he", "head", "headed",
    "heading", "headline", "headquarters", "heal", "healing", "health",
    "healthy", "heap", "hear", "heard", "hearing", "heart", "heat", "heated",
    "heating", "heaven", "heavenly", "heavily", "heavy", "hedge", "heel",
    "height", "heighten", "heir", "helicopter", "hell", "hello", "help",
    "helpful", "helpless", "hence", "her", "herb", "herd", "here", "heritage",
    "hero", "heroic", "heroine", "herself", "hesitant", "hesitate",
    "hesitation", "hey", "hi", "hidden", "hide", "hierarchy", "high",
    "highlight", "highly", "highway", "hike", "hill", "hillside", "him",
    "himself", "hint", "hip", "hire", "his", "historian", "historic",
    "historical", "historically", "history", "hit", "hobby", "hockey", "hold",
    "holder", "holding", "hole", "holiday", "hollow", "holy", "home",
    "homeland", "homeless", "homework", "honest", "honestly", "honesty",
    "honey", "honor", "honour", "honourable", "hood", "hook", "hope",
    "hopeful", "hopefully", "hopeless", "horizon", "horizontal", "horn",
    "horrible", "horror", "horse", "hospital", "hospitality", "host",
    "hostage", "hostile", "hostility", "hot", "hotel", "hour", "hourly",
    "house", "household", "housewife", "housing", "how", "however", "hug",
    "huge", "hull", "human", "humanitarian", "humanity", "humble", "humid",
    "humiliate", "humiliation", "humor", "humour", "humorous", "hundred",
    "hunger", "hungry", "hunt", "hunter", "hunting", "hurdle", "hurl",
    "hurry", "hurt", "husband", "hut", "hydrogen", "hypothesis",
    "ice", "icon", "idea", "ideal", "ideally", "identical", "identification",
    "identify", "identity", "ideology", "ignorance", "ignorant", "ignore",
    "ill", "illegal", "illegally", "illness", "illuminate", "illusion",
    "illustrate", "illustration", "image", "imagery", "imaginary",
    "imagination", "imaginative", "imagine", "immediate", "immediately",
    "immense", "immensely", "immigrant", "immigration", "immune", "immunity",
    "impact", "impair", "implement", "implementation", "implication",
    "implicit", "imply", "import", "importance", "important", "importantly",
    "impose", "impossible", "impress", "impressed", "impression",
    "impressive", "imprison", "imprisonment", "improve", "improved",
    "improvement", "impulse", "in", "inability", "inadequate", "inappropriate",
    "incentive", "inch", "incident", "inclined", "include", "included",
    "including", "inclusion", "income", "incorporate", "increase",
    "increased", "increasingly", "incredible", "incredibly", "incur",
    "indeed", "independence", "independent", "independently", "index",
    "indicate", "indication", "indicator", "indigenous", "indirect",
    "individual", "individually", "industrial", "industrialist", "industry",
    "inequality", "inevitable", "inevitably", "infant", "infection",
    "inflation", "influence", "influential", "inform", "informal",
    "information", "infrastructure", "ingredient", "inhabit", "inhabitant",
    "inherent", "inherit", "inheritance", "initial", "initially", "initiate",
    "initiative", "injection", "injure", "injured", "injury", "injustice",
    "inn", "inner", "innocence", "innocent", "innovation", "innovative",
    "input", "inquiry", "insect", "insert", "inside", "insider", "insist",
    "insistence", "inspection", "inspector", "inspiration", "inspire",
    "install", "installation", "instance", "instant", "instantly", "instead",
    "instinct", "institute", "institution", "institutional", "instruction",
    "instructor", "instrument", "instrumental", "insufficient", "insurance",
    "insure", "intact", "intake", "integrate", "integrated", "integration",
    "integrity", "intellectual", "intelligence", "intelligent", "intend",
    "intended", "intense", "intensely", "intensity", "intensive", "intent",
    "intention", "interact", "interaction", "interest", "interested",
    "interesting", "interim", "interior", "internal", "international",
    "internet", "interpret", "interpretation", "intervention", "interview",
    "intimate", "into", "introduce", "introduction", "invade", "invasion",
    "invent", "invention", "inventor", "inventory", "invest", "investigate",
    "investigation", "investigator", "investment", "investor", "invisible",
    "invitation", "invite", "involve", "involved", "involvement", "iron",
    "ironic", "irony", "irregular", "irrelevant", "irritate", "island",
    "isolate", "isolated", "isolation", "issue", "it", "item", "its",
    "itself", "ivory",
    "jacket", "jail", "jam", "january", "jar", "jaw", "jazz", "jealous",
    "jealousy", "jeans", "jerk", "jersey", "jet", "jewel", "jewellery",
    "jewelry", "job", "jockey", "jog", "join", "joint", "jointly", "joke",
    "jolly", "journal", "journalism", "journalist", "journey", "joy", "judge",
    "judgment", "judgement", "juice", "juicy", "july", "jump", "junction",
    "june", "jungle", "junior", "jury", "just", "justice", "justification",
    "justify", "juvenile",
    "keen", "keep", "keeper", "keeping", "kept", "kernel", "kettle", "key",
    "keyboard", "kick", "kid", "kidnap", "kidney", "kill", "killer", "killing",
    "kilometer", "kilometre", "kind", "kindly", "kindness", "king", "kingdom",
    "kiss", "kit", "kitchen", "knee", "kneel", "knew", "knife", "knight",
    "knit", "knob", "knock", "knot", "know", "knowing", "knowledge", "known",
    "lab", "label", "labor", "laboratory", "labour", "lace", "lack", "lad",
    "ladder", "lady", "lag", "laid", "lake", "lamb", "lame", "lamp", "land",
    "landing", "landlord", "landmark", "landscape", "lane", "language", "lap",
    "large", "largely", "laser", "lass", "last", "lasting", "late", "lately",
    "lateral", "latest", "latter", "laugh", "laughter", "launch", "laundry",
    "lava", "lavish", "law", "lawn", "lawsuit", "lawyer", "lay", "layer",
    "layout", "lazy", "lead", "leader", "leadership", "leading", "leaf",
    "leaflet", "league", "leak", "lean", "leap", "learn", "learned",
    "learner", "learning", "lease", "least", "leather", "leave", "lecture",
    "lecturer", "led", "left", "leg", "legacy", "legal", "legally", "legend",
    "legendary", "legislation", "legislative", "legislature", "legitimate",
    "leisure", "lemon", "lend", "length", "lens", "lent", "lesson", "let",
    "lethal", "letter", "level", "liberal", "liberate", "liberation",
    "liberty", "librarian", "library", "licence", "license", "lid", "lie",
    "lieutenant", "life", "lifestyle", "lifetime", "lift", "light", "lighten",
    "lighting", "lightly", "lightweight", "like", "likelihood", "likely",
    "likewise", "limb", "lime", "limestone", "limit", "limitation", "limited",
    "limp", "line", "linear", "linen", "linger", "link", "lion", "lip",
    "liquid", "list", "listen", "listener", "literacy", "literal", "literally",
    "literary", "literature", "litigation", "little", "live", "lively",
    "liver", "living", "load", "loaf", "loan", "lobby", "local", "locally",
    "locate", "location", "lock", "locomotive", "lodge", "log", "logic",
    "logical", "lone", "lonely", "long", "longer", "longest", "longing",
    "look", "loop", "loose", "loosely", "lord", "lose", "loser", "loss",
    "lost", "lot", "lots", "loud", "loudly", "lounge", "love", "lovely",
    "lover", "low", "lower", "loyal", "loyalty", "luck", "lucky", "luggage",
    "lump", "lunch", "lung", "lure", "lurk", "lush", "luxury",
    "machine", "machinery", "mad", "magazine", "magic", "magical",
    "magistrate", "magnificent", "magnitude", "maid", "maiden", "mail",
    "main", "mainland", "mainly", "mainstream", "maintain", "maintenance",
    "major", "majority", "make", "maker", "makeup", "male", "mall",
    "mammal", "man", "manage", "management", "manager", "mandate", "manifest",
    "manipulate", "manipulation", "mankind", "manner", "manor", "mansion",
    "manual", "manufacture", "manufacturer", "manufacturing", "manuscript",
    "many", "map", "maple", "marathon", "marble", "march", "margin",
    "marginal", "marine", "mark", "marked", "marker", "market", "marketing",
    "marketplace", "marriage", "married", "marry", "marsh", "mask", "mass",
    "massacre", "massive", "master", "mate", "material", "math",
    "mathematical", "mathematics", "matter", "mature", "maturity", "maximum",
    "may", "maybe", "mayor", "me", "meadow", "meal", "mean", "meaning",
    "meaningful", "means", "meant", "meanwhile", "measure", "measurement",
    "meat", "mechanic", "mechanical", "mechanism", "medal", "media", "median",
    "medical", "medication", "medicine", "medieval", "medium", "meet",
    "meeting", "melody", "melt", "member", "membership", "membrane", "memoir",
    "memorable", "memorial", "memory", "men", "menace", "mend", "mental",
    "mentally", "mention", "mentor", "menu", "merchant", "mercy", "mere",
    "merely", "merge", "merger", "merit", "mess", "message", "messenger",
    "messy", "met", "metal", "metaphor", "method", "methodology", "mid",
    "middle", "midnight", "midst", "might", "mighty", "migration", "mild",
    "mildly", "mile", "milestone", "militant", "military", "militia", "milk",
    "mill", "millennium", "million", "millionaire", "mind", "mine", "miner",
    "mineral", "minimal", "minimize", "minimum", "minister", "ministry",
    "minor", "minority", "minute", "miracle", "mirror", "miserable", "misery",
    "mislead", "misleading", "miss", "missile", "missing", "mission",
    "missionary", "mistake", "mistaken", "mix", "mixed", "mixture", "moan",
    "mob", "mobile", "mobility", "mode", "model", "moderate", "moderately",
    "modern", "modernize", "modest", "modify", "module", "molecule", "mom",
    "moment", "momentum", "monarch", "monarchy", "monastery", "monday",
    "monetary", "money", "monitor", "monk", "monkey", "monopoly", "monster",
    "month", "monthly", "monument", "mood", "moon", "moonlight", "moral",
    "morale", "morality", "more", "moreover", "morning", "mortality",
    "mortgage", "mosque", "most", "mostly", "motel", "mother", "motion",
    "motivate", "motivation", "motive", "motor", "mount", "mountain", "mourn",
    "mourning", "mouse", "mouth", "move", "movement", "movie", "moving",
    "much", "mud", "multiple", "municipal", "murder", "murderer", "murmur",
    "muscle", "museum", "music", "musical", "musician", "muslim", "must",
    "mutual", "mutually", "my", "mystery", "mysterious", "mysteriously",
    "myth", "mythology",
    "nail", "naked", "name", "namely", "narrative", "narrator", "narrow",
    "nasty", "nation", "national", "nationalist", "nationality",
    "nationwide", "native", "natural", "naturally", "nature", "naval", "navy",
    "near", "nearby", "nearly", "neat", "neatly", "necessarily", "necessary",
    "necessity", "neck", "necklace", "need", "needle", "negative",
    "negatively", "neglect", "negotiate", "negotiation", "negotiator",
    "neighbor", "neighbour", "neighbourhood", "neighborhood", "neither",
    "nerve", "nervous", "nervously", "nest", "net", "network", "neutral",
    "never", "nevertheless", "new", "newcomer", "newly", "news", "newspaper",
    "next", "nice", "nicely", "niche", "night", "nightmare", "nine",
    "nineteen", "nineteenth", "ninety", "ninth", "no", "noble", "nobody",
    "nod", "noise", "noisy", "nominal", "nominate", "nomination", "none",
    "nonetheless", "nonsense", "noon", "nor", "norm", "normal", "normally",
    "north", "northeast", "northern", "northwest", "nose", "not", "notably",
    "note", "notebook", "nothing", "notice", "noticeable", "notion", "novel",
    "novelist", "novelty", "november", "now", "nowadays", "nowhere", "nuclear",
    "nucleus", "nuisance", "number", "numerous", "nun", "nurse", "nursery",
    "nursing", "nut", "nutrition",
    "oak", "oath", "obey", "object", "objection", "objective", "obligation",
    "oblige", "observation", "observe", "observer", "obsess", "obsession",
    "obstacle", "obtain", "obvious", "obviously", "occasion", "occasional",
    "occasionally", "occupation", "occupy", "occur", "occurrence", "ocean",
    "october", "odd", "odds", "of", "off", "offence", "offend", "offender",
    "offense", "offensive", "offer", "offering", "office", "officer",
    "official", "officially", "offset", "offspring", "often", "oh", "oil",
    "ok", "okay", "old", "olive", "on", "once", "one", "ongoing", "onion",
    "online", "only", "onset", "onto", "open", "opening", "openly", "opera",
    "operate", "operating", "operation", "operational", "operator", "opinion",
    "opponent", "opportunity", "oppose", "opposed", "opposing", "opposite",
    "opposition", "opt", "optical", "optimism", "optimistic", "option",
    "optional", "or", "oral", "orange", "orbit", "orchestra", "ordeal",
    "order", "ordinary", "organ", "organic", "organisation", "organization",
    "organize", "orientation", "origin", "original", "originally", "orphan",
    "other", "otherwise", "ought", "ounce", "our", "ours", "ourselves", "out",
    "outbreak", "outcome", "outdoor", "outdoors", "outer", "outfit", "output",
    "outrage", "outrageous", "outside", "outsider", "outstanding", "over",
    "overall", "overcome", "overlook", "overnight", "overseas", "oversee",
    "overturn", "overwhelm", "overwhelming", "owe", "own", "owner",
    "ownership", "oxygen",
    "pace", "pack", "package", "packed", "pad", "page", "paid", "pain",
    "painful", "paint", "painter", "painting", "pair", "pal", "palace",
    "pale", "palm", "pan", "panel", "panic", "panorama", "pants", "paper",
    "parade", "paradise", "paragraph", "parallel", "parcel", "pardon",
    "parent", "parental", "parish", "park", "parking", "parliament",
    "parliamentary", "part", "partial", "partially", "participant",
    "participate", "participation", "particle", "particular", "particularly",
    "partly", "partner", "partnership", "party", "pass", "passage",
    "passenger", "passing", "passion", "passionate", "passive", "passport",
    "past", "paste", "patch", "path", "patience", "patient", "patiently",
    "patrol", "patron", "pattern", "pause", "pave", "pavement", "paw", "pay",
    "payment", "peace", "peaceful", "peacefully", "peak", "pear", "pearl",
    "peasant", "peculiar", "peer", "penalty", "pending", "penetrate",
    "pension", "pensioner", "people", "pepper", "per", "perceive", "percent",
    "percentage", "perception", "perfect", "perfection", "perfectly",
    "perform", "performance", "performer", "perfume", "perhaps", "peril",
    "period", "permanent", "permanently", "permission", "permit", "persist",
    "persistent", "person", "personal", "personality", "personally",
    "personnel", "perspective", "persuade", "pet", "petition", "petrol",
    "petty", "phase", "phenomenon", "philosopher", "philosophical",
    "philosophy", "phone", "photo", "photograph", "photographer",
    "photography", "phrase", "physical", "physically", "physician", "physics",
    "piano", "pick", "picture", "pie", "piece", "pier", "pig", "pile",
    "pilgrim", "pill", "pillar", "pillow", "pilot", "pin", "pine", "pink",
    "pioneer", "pipe", "pipeline", "pitch", "pity", "pizza", "place",
    "placement", "plain", "plainly", "plan", "plane", "planet", "planner",
    "planning", "plant", "plantation", "plaster", "plastic", "plate",
    "platform", "plausible", "play", "player", "playground", "plea", "plead",
    "pleasant", "please", "pleased", "pleasing", "pleasure", "pledge",
    "plenty", "plot", "plough", "plunge", "plus", "pocket", "poem", "poet",
    "poetry", "point", "pointed", "poison", "polar", "pole", "police",
    "policeman", "policewoman", "policy", "polish", "polite", "politely",
    "political", "politically", "politician", "politics", "poll", "pollution",
    "pond", "pool", "poor", "poorly", "pop", "popular", "popularity",
    "population", "porch", "port", "portal", "portion", "portrait", "portray",
    "pose", "position", "positive", "positively", "possess", "possession",
    "possibility", "possible", "possibly", "post", "postal", "poster",
    "postpone", "pot", "potato", "potential", "potentially", "pottery",
    "poultry", "pound", "pour", "poverty", "powder", "power", "powerful",
    "practical", "practically", "practice", "practise", "practitioner",
    "praise", "pray", "prayer", "preach", "preacher", "precaution", "precede",
    "precedent", "precious", "precise", "precisely", "precision", "predict",
    "prediction", "predominantly", "prefer", "preference", "pregnancy",
    "pregnant", "prejudice", "preliminary", "premier", "premiere", "premise",
    "premium", "preparation", "prepare", "prepared", "prescribe",
    "prescription", "presence", "present", "presentation", "presently",
    "preservation", "preserve", "presidency", "president", "presidential",
    "press", "pressure", "presumably", "presume", "pretend", "pretty",
    "prevail", "prevalent", "prevent", "prevention", "previous", "previously",
    "price", "pride", "priest", "primarily", "primary", "prime", "primitive",
    "prince", "princess", "principal", "principle", "print", "printer",
    "printing", "prior", "priority", "prison", "prisoner", "privacy",
    "private", "privately", "privilege", "privileged", "prize", "probable",
    "probably", "probe", "problem", "problematic", "procedure", "proceed",
    "proceeding", "process", "procession", "processor", "proclaim", "produce",
    "producer", "product", "production", "productive", "productivity",
    "profession", "professional", "professionally", "professor", "profile",
    "profit", "profitable", "profound", "profoundly", "program", "programme",
    "programmer", "programming", "progress", "progressive", "prohibit",
    "project", "projection", "prominent", "promise", "promising", "promote",
    "promoter", "promotion", "prompt", "promptly", "prone", "pronounce",
    "pronounced", "proof", "propaganda", "proper", "properly", "property",
    "proportion", "proposal", "propose", "proposed", "proposition",
    "prosecutor", "prospect", "prospective", "prosperity", "prosperous",
    "protect", "protection", "protective", "protein", "protest", "protester",
    "proud", "proudly", "prove", "proven", "provide", "provided", "provider",
    "province", "provincial", "provision", "provoke", "psychological",
    "psychologist", "psychology", "pub", "public", "publication", "publicity",
    "publicly", "publish", "publisher", "publishing", "pudding", "pull",
    "pulse", "pump", "punch", "punish", "punishment", "punk", "pupil",
    "puppet", "purchase", "pure", "purely", "purple", "purpose", "pursue",
    "pursuit", "push", "put", "puzzle", "puzzled",
    "qualification", "qualified", "qualify", "quality", "quantity", "quantum",
    "quarter", "quarterly", "queen", "query", "quest", "question",
    "questionnaire", "queue", "quick", "quickly", "quid", "quiet", "quietly",
    "quilt", "quit", "quite", "quota", "quotation", "quote",
    "rabbit", "race", "racial", "racism", "racist", "rack", "radar",
    "radiation", "radical", "radically", "radio", "rage", "raid", "rail",
    "railroad", "railway", "rain", "rainbow", "rainfall", "raise", "rally",
    "ramification", "ranch", "random", "randomly", "range", "rank", "rapid",
    "rapidly", "rare", "rarely", "rat", "rate", "rather", "rating", "ratio",
    "rational", "raw", "ray", "reach", "react", "reaction", "read", "reader",
    "readily", "reading", "ready", "real", "realistic", "reality",
    "realization", "realize", "really", "realm", "rear", "reason",
    "reasonable", "reasonably", "reasoning", "rebel", "rebellion", "rebuild",
    "recall", "receipt", "receive", "receiver", "recent", "recently",
    "reception", "recipe", "recipient", "recognition", "recognize",
    "recommend", "recommendation", "reconcile", "reconciliation", "record",
    "recorder", "recording", "recover", "recovery", "recruit", "recruitment",
    "red", "reduce", "reduction", "refer", "referee", "reference",
    "referendum", "reflect", "reflection", "reform", "refugee", "refusal",
    "refuse", "regain", "regard", "regarding", "regardless", "regime",
    "region", "regional", "register", "registration", "regret", "regular",
    "regularly", "regulate", "regulation", "regulator", "regulatory",
    "rehabilitation", "reign", "reinforce", "reject", "rejection", "relate",
    "related", "relation", "relationship", "relative", "relatively",
    "relax", "relaxation", "relaxed", "relay", "release", "relevance",
    "relevant", "reliability", "reliable", "relief", "relieve", "religion",
    "religious", "reluctance", "reluctant", "reluctantly", "rely", "remain",
    "remainder", "remaining", "remains", "remark", "remarkable", "remarkably",
    "remedy", "remember", "remind", "reminder", "remote", "remotely",
    "removal", "remove", "render", "renew", "renewal", "renowned", "rent",
    "rental", "repair", "repeat", "repeated", "repeatedly", "repel",
    "repetition", "replace", "replacement", "replica", "reply", "report",
    "reporter", "reporting", "represent", "representation", "representative",
    "reproduce", "reproduction", "republic", "republican", "reputation",
    "request", "require", "required", "requirement", "rescue", "research",
    "researcher", "resemble", "reservation", "reserve", "reservoir",
    "residence", "resident", "residential", "resign", "resignation", "resist",
    "resistance", "resolution", "resolve", "resort", "resource",
    "respect", "respectable", "respective", "respectively", "respond",
    "response", "responsibility", "responsible", "responsive", "rest",
    "restaurant", "restoration", "restore", "restraint", "restrict",
    "restriction", "result", "resulting", "resume", "retail", "retailer",
    "retain", "retention", "retire", "retired", "retirement", "retreat",
    "retrieve", "return", "reveal", "revelation", "revenge", "revenue",
    "reverse", "review", "reviewer", "revision", "revival", "revolution",
    "revolutionary", "reward", "rhetoric", "rhythm", "rib", "ribbon", "rice",
    "rich", "rid", "ride", "rider", "ridge", "ridiculous", "rifle", "right",
    "rigid", "ring", "riot", "rip", "rise", "rising", "risk", "risky",
    "ritual", "rival", "rivalry", "river", "road", "roadside", "roar", "rob",
    "robbery", "robe", "robot", "robust", "rock", "rocket", "rod", "role",
    "roll", "romantic", "roof", "room", "root", "rope", "rose", "roster",
    "rotate", "rotation", "rotten", "rough", "roughly", "round", "route",
    "routine", "row", "royal", "royalty", "rub", "rubber", "rubbish", "rude",
    "rug", "ruin", "rule", "ruler", "ruling", "rumor", "rumour", "run",
    "runner", "running", "rural", "rush", "ruthless",
    "sacred", "sacrifice", "sad", "saddle", "sadly", "sadness", "safe",
    "safely", "safety", "sage", "said", "sail", "sailor", "saint", "sake",
    "salad", "salary", "sale", "salmon", "salon", "salt", "salvation",
    "same", "sample", "sanction", "sand", "sandwich", "satellite",
    "satisfaction", "satisfactory", "satisfied", "satisfy", "satisfying",
    "saturday", "sauce", "save", "saving", "say", "scale", "scan", "scandal",
    "scar", "scarce", "scarcely", "scare", "scared", "scatter", "scattered",
    "scenario", "scene", "scenery", "scent", "schedule", "scheme", "scholar",
    "scholarship", "school", "science", "scientific", "scientist", "scope",
    "score", "scout", "scramble", "scrap", "scrape", "scratch", "scream",
    "screen", "screening", "screenplay", "screw", "script", "scripture",
    "scroll", "scrutiny", "sculpture", "sea", "seal", "search", "season",
    "seasonal", "seat", "second", "secondary", "secondly", "secret",
    "secretariat", "secretary", "secretly", "section", "sector", "secular",
    "secure", "securely", "security", "see", "seed", "seek", "seem",
    "seemingly", "seen", "segment", "seize", "select", "selection", "self",
    "sell", "seller", "semester", "senate", "senator", "send", "sender",
    "senior", "sensation", "sense", "sensible", "sensitive", "sensitivity",
    "sentence", "sentiment", "separate", "separated", "separately",
    "separation", "september", "sequence", "series", "serious", "seriously",
    "servant", "serve", "server", "service", "session", "set", "setting",
    "settle", "settled", "settlement", "settler", "seven", "seventeen",
    "seventeenth", "seventh", "seventy", "several", "severe", "severely",
    "severity", "sew", "sex", "sexual", "sexually", "shade", "shadow",
    "shaft", "shake", "shaky", "shall", "shallow", "shame", "shape", "share",
    "shareholder", "sharp", "sharply", "shatter", "shave", "she", "shed",
    "sheer", "sheet", "shelf", "shell", "shelter", "shepherd", "sheriff",
    "shield", "shift", "shine", "shiny", "ship", "shipment", "shirt", "shit",
    "shiver", "shock", "shocked", "shocking", "shoe", "shoot", "shooting",
    "shop", "shopping", "shore", "short", "shortage", "shortcoming",
    "shortly", "shot", "should", "shoulder", "shout", "shove", "show",
    "showcase", "shower", "shrink", "shrug", "shut", "shuttle", "shy", "sick",
    "side", "sidewalk", "sigh", "sight", "sign", "signal", "signature",
    "significance", "significant", "significantly", "silence", "silent",
    "silently", "silk", "silly", "silver", "similar", "similarity",
    "similarly", "simple", "simplicity", "simplify", "simply", "simulate",
    "simulation", "simultaneous", "simultaneously", "sin", "since", "sincere",
    "sincerely", "sing", "singer", "singing", "single", "sink", "sir", "sit",
    "site", "sitting", "situated", "situation", "six", "sixteen", "sixteenth",
    "sixth", "sixty", "size", "skeptic", "skeptical", "sketch", "ski",
    "skill", "skilled", "skin", "skinny", "skip", "skirt", "skull", "sky",
    "slap", "slash", "slate", "slaughter", "slave", "slavery", "sleep",
    "sleeping", "sleeve", "slender", "slice", "slide", "slight", "slightly",
    "slim", "slip", "slogan", "slope", "slot", "slow", "slowly", "slump",
    "small", "smaller", "smallest", "smart", "smash", "smell", "smile",
    "smoke", "smoking", "smooth", "smoothly", "snap", "snatch", "sneak",
    "snow", "so", "soak", "soap", "soar", "sob", "sober", "soccer", "social",
    "socialism", "socialist", "socially", "society", "sock", "sodium", "sofa",
    "soft", "soften", "softly", "software", "soil", "solar", "soldier",
    "sole", "solely", "solemn", "solid", "solidarity", "solo", "solution",
    "solve", "some", "somebody", "someday", "somehow", "someone", "something",
    "sometimes", "somewhat", "somewhere", "son", "song", "soon", "sooner",
    "sophisticated", "sorry", "sort", "soul", "sound", "soup", "source",
    "south", "southeast", "southern", "southwest", "sovereign", "sovereignty",
    "space", "span", "spare", "spark", "speak", "speaker", "special",
    "specialist", "specialize", "specialized", "specially", "species",
    "specific", "specifically", "specification", "specimen", "spectacular",
    "spectator", "spectrum", "speech", "speed", "spell", "spelling", "spend",
    "spending", "sphere", "spice", "spider", "spike", "spill", "spin",
    "spine", "spiral", "spirit", "spiritual", "spit", "splash", "splendid",
    "split", "spokesman", "spokesperson", "sponsor", "spontaneous", "spoon",
    "sport", "sporting", "spot", "spotlight", "spouse", "spray", "spread",
    "spring", "spy", "squad", "squadron", "square", "squeeze", "stability",
    "stable", "stack", "stadium", "staff", "stage", "stagger", "stain",
    "stair", "staircase", "stairs", "stake", "stale", "stall", "stamp",
    "stance", "stand", "standard", "standing", "standpoint", "star", "stare",
    "stark", "start", "starting", "startling", "starvation", "starve",
    "state", "statement", "station", "statistic", "statistical", "statue",
    "status", "statute", "statutory", "stay", "steadily", "steady", "steal",
    "steam", "steel", "steep", "steer", "stem", "step", "stereotype",
    "sterling", "stern", "stick", "sticky", "stiff", "still", "stimulate",
    "stimulus", "sting", "stir", "stock", "stomach", "stone", "stood",
    "stool", "stop", "storage", "store", "storm", "story", "stout",
    "straight", "straightforward", "strain", "strand", "strange", "strangely",
    "stranger", "strategic", "strategist", "strategy", "straw", "strawberry",
    "stray", "streak", "stream", "street", "strength", "strengthen", "stress",
    "stressful", "stretch", "strict", "strictly", "stride", "strike",
    "striker", "striking", "string", "strip", "stripe", "strive", "stroke",
    "stroll", "strong", "strongly", "structural", "structure", "struggle",
    "stubborn", "stuck", "student", "studio", "study", "stuff", "stumble",
    "stun", "stunning", "stupid", "style", "subject", "submission", "submit",
    "subsequent", "subsequently", "substance", "substantial", "substantially",
    "subtle", "suburb", "suburban", "succeed", "success", "successful",
    "successfully", "successive", "successor", "such", "suck", "sudden",
    "suddenly", "sue", "suffer", "suffering", "sufficient", "sufficiently",
    "sugar", "suggest", "suggestion", "suicide", "suit", "suitable", "suite",
    "suited", "sum", "summary", "summer", "summit", "summon", "sun",
    "sunday", "sunlight", "sunny", "sunrise", "sunset", "sunshine", "super",
    "superb", "superintendent", "superior", "supervise", "supervision",
    "supervisor", "supper", "supplement", "supplementary", "supplier",
    "supply", "support", "supporter", "suppose", "supposed", "supposedly",
    "suppress", "supreme", "sure", "surely", "surface", "surgeon", "surgery",
    "surplus", "surprise", "surprised", "surprising", "surprisingly",
    "surrender", "surround", "surrounding", "surveillance", "survey",
    "survival", "survive", "survivor", "suspect", "suspend", "suspension",
    "suspicion", "suspicious", "sustain", "sustainable", "swallow", "swamp",
    "swap", "swear", "sweat", "sweater", "sweep", "sweet", "swell", "swept",
    "swift", "swiftly", "swim", "swimmer", "swimming", "swing", "switch",
    "sword", "swore", "sworn", "symbol", "symbolic", "sympathetic",
    "sympathy", "symptom", "syndrome", "syntax", "synthesis", "system",
    "systematic", "systematically",
    "table", "tablet", "tactic", "tactical", "tail", "tailor", "take",
    "tale", "talent", "talented", "talk", "tall", "tank", "tap", "tape",
    "target", "tariff", "task", "taste", "tax", "taxation", "taxpayer", "tea",
    "teach", "teacher", "teaching", "team", "tear", "tease", "technical",
    "technically", "technique", "technological", "technology", "teenager",
    "telephone", "television", "tell", "temper", "temperature", "temple",
    "temporarily", "temporary", "tempt", "temptation", "ten", "tenant",
    "tend", "tendency", "tender", "tennis", "tense", "tension", "tent",
    "tenure", "term", "terminal", "terminate", "terms", "terrace", "terrain",
    "terrible", "terribly", "terrific", "terrified", "territorial",
    "territory", "terror", "terrorism", "terrorist", "test", "testament",
    "testify", "testimony", "testing", "text", "textbook", "textile",
    "texture", "than", "thank", "thankful", "thanks", "thanksgiving", "that",
    "the", "theater", "theatre", "theatrical", "theft", "their", "theirs",
    "them", "theme", "themselves", "then", "theology", "theoretical",
    "theory", "therapy", "there", "thereafter", "thereby", "therefore",
    "these", "thesis", "they", "thick", "thicken", "thickness", "thief",
    "thigh", "thin", "thing", "think", "thinker", "thinking", "third",
    "thirst", "thirsty", "thirteen", "thirteenth", "thirty", "this",
    "thorough", "thoroughly", "those", "though", "thought", "thoughtful",
    "thousand", "thread", "threat", "threaten", "threatening", "three",
    "threshold", "thrill", "thrilling", "thrive", "throat", "throne",
    "through", "throughout", "throw", "thrown", "thrust", "thumb", "thunder",
    "thursday", "thus", "tick", "ticket", "tide", "tidy", "tie", "tight",
    "tighten", "tightly", "tile", "till", "timber", "time", "timeline",
    "timing", "tin", "tiny", "tip", "tire", "tired", "tissue", "title", "to",
    "toast", "tobacco", "today", "toe", "together", "tolerance", "tolerant",
    "tolerate", "toll", "tomato", "tomb", "tomorrow", "ton", "tone", "tongue",
    "tonight", "too", "tool", "tooth", "top", "topic", "torch", "torn",
    "torture", "toss", "total", "totally", "touch", "touched", "touching",
    "tough", "tour", "tourism", "tourist", "tournament", "toward", "towards",
    "towel", "tower", "town", "toxic", "toy", "trace", "track", "trade",
    "trademark", "trader", "tradition", "traditional", "traditionally",
    "traffic", "tragedy", "tragic", "trail", "trailer", "train", "trainer",
    "training", "trait", "transfer", "transform", "transformation", "transit",
    "transition", "translate", "translation", "transmission", "transmit",
    "transparency", "transparent", "transport", "transportation", "trap",
    "trash", "trauma", "travel", "traveler", "traveller", "tray", "treasure",
    "treasury", "treat", "treatment", "treaty", "tree", "tremble",
    "tremendous", "tremendously", "trench", "trend", "trial", "triangle",
    "tribe", "tribunal", "tribute", "trick", "tricky", "trigger", "trillion",
    "trim", "trio", "trip", "triple", "triumph", "trivial", "troop",
    "tropical", "trouble", "troubled", "troubling", "trouser", "trousers",
    "truck", "true", "truly", "trump", "trunk", "trust", "trustee", "truth",
    "try", "tube", "tuck", "tuesday", "tumble", "tumor", "tumour", "tune",
    "tunnel", "turn", "tutor", "twelve", "twelfth", "twenty", "twentieth",
    "twice", "twin", "twist", "two", "type", "typical", "typically",
    "ugly", "ultimate", "ultimately", "umbrella", "unable", "unacceptable",
    "unanimous", "uncertain", "uncertainty", "uncle", "unclear", "uncover",
    "under", "undergo", "underground", "underline", "undermine", "underneath",
    "understand", "understanding", "undertake", "underwater", "underway",
    "undesirable", "undo", "undoubtedly", "undue", "unemployment", "unfair",
    "unfairly", "unfortunate", "unfortunately", "unhappy", "uniform",
    "unify", "union", "unique", "uniquely", "unit", "unite", "united",
    "unity", "universal", "universe", "university", "unknown", "unless",
    "unlike", "unlikely", "unlock", "unnecessary", "unprecedented",
    "unpleasant", "unpredictable", "unreasonable", "unrest", "until",
    "unusual", "unusually", "unwanted", "unwell", "unwilling", "up", "update",
    "upgrade", "upon", "upper", "upset", "upstairs", "upstream", "urban",
    "urge", "urgency", "urgent", "urgently", "us", "usage", "use", "used",
    "useful", "user", "usual", "usually", "utility", "utilize", "utter",
    "utterly",
    "vacancy", "vacant", "vacation", "vaccine", "vague", "vaguely", "vain",
    "valid", "validate", "validity", "valley", "valuable", "value", "valve",
    "van", "vanish", "variable", "variation", "varied", "variety", "various",
    "vary", "vast", "vastly", "vegetable", "vegetation", "vehicle", "veil",
    "vein", "velocity", "vendor", "venture", "venue", "verb", "verbal",
    "verdict", "verge", "verify", "verse", "version", "versus", "vertical",
    "very", "vessel", "veteran", "via", "viable", "vibrant", "vice",
    "vicinity", "victim", "victory", "video", "view", "viewer", "vigorous",
    "vigorously", "village", "villager", "villain", "violation", "violence",
    "violent", "violently", "virgin", "virtual", "virtually", "virtue",
    "visible", "vision", "visit", "visitor", "visual", "vital", "vivid",
    "vocabulary", "vocal", "voice", "volatile", "volume", "voluntary",
    "volunteer", "vote", "voter", "voting", "vulnerable",
    "wage", "wagon", "waist", "wait", "wake", "walk", "walker", "walking",
    "wall", "wallet", "wander", "want", "war", "ward", "wardrobe",
    "warehouse", "warfare", "warm", "warmth", "warn", "warning", "warrant",
    "warranty", "warrior", "wash", "waste", "watch", "water", "waterfall",
    "wave", "wax", "way", "we", "weak", "weaken", "weakness", "wealth",
    "wealthy", "weapon", "wear", "wearing", "weather", "web", "website",
    "wedding", "wednesday", "weed", "week", "weekday", "weekend", "weekly",
    "weep", "weigh", "weight", "weird", "welcome", "welfare", "well", "west",
    "western", "wet", "whale", "what", "whatever", "wheat", "wheel", "when",
    "whenever", "where", "whereas", "wherever", "whether", "which",
    "whichever", "while", "whilst", "whip", "whisky", "whisper", "whistle",
    "white", "who", "whole", "wholesale", "wholly", "whom", "whose", "why",
    "wicked", "wide", "widely", "widen", "widespread", "widow", "width",
    "wife", "wild", "wildly", "wildlife", "will", "willing", "willingly",
    "willingness", "win", "wind", "window", "wine", "wing", "winner",
    "winning", "winter", "wipe", "wire", "wireless", "wisdom", "wise",
    "wish", "wit", "witch", "with", "withdraw", "withdrawal", "withdrawn",
    "within", "without", "witness", "wolf", "woman", "women", "wonder",
    "wonderful", "wonderfully", "wood", "wooden", "wool", "word", "wore",
    "work", "worker", "workforce", "working", "workout", "workplace",
    "workshop", "world", "worldwide", "worm", "worried", "worry",
    "worrying", "worse", "worsen", "worship", "worst", "worth", "worthwhile",
    "worthy", "would", "wound", "wounded", "wrap", "wrath", "wreck",
    "wrestle", "wrist", "write", "writer", "writing", "written", "wrong",
    "wrongly",
    "yacht", "yard", "yeah", "year", "yearly", "yell", "yellow", "yes",
    "yesterday", "yet", "yield", "you", "young", "youngster", "your",
    "yours", "yourself", "yourselves", "youth", "youthful",
    "zeal", "zero", "zone", "zoo",
    "ain", "aren", "can", "couldn", "didn", "doesn", "don", "hadn", "hasn",
    "haven", "isn", "let", "mustn", "shan", "shouldn", "wasn", "weren",
    "won", "wouldn",
    "alright", "anyone", "backstory", "bartender", "bathroom", "beat",
    "blackout", "bodyguard", "boyfriend", "briefcase", "buddy", "cab",
    "camera", "cellphone", "clipboard", "closet", "confrontation", "cop",
    "cops", "corpse", "courthouse", "cowboy", "crime", "crossroads",
    "dashboard", "detective", "diner", "doorbell", "downtown", "driveway",
    "earpiece", "elevator", "ex", "expressway", "eyewitness", "fella",
    "flashback", "flashlight", "forensic", "freeway", "gangster", "getaway",
    "girlfriend", "gonna", "gotta", "gunshot", "handcuff", "handcuffs",
    "handgun", "headlight", "headlights", "highway", "hitman", "holster",
    "hoodie", "hostage", "housewife", "interrogation", "kidnapper",
    "laptop", "lineup", "lookout", "loudspeaker", "makeshift", "mic",
    "microphone", "montage", "motorcycle", "mugshot", "newsroom",
    "nightclub", "offscreen", "onscreen", "overpass", "paramedic",
    "passenger", "passageway", "patrol", "payphone", "penthouse",
    "pickup", "plainclothes", "playlist", "precinct", "revolver", "ringtone",
    "roadblock", "rooftop", "screenplay", "setup", "shootout", "shotgun",
    "showdown", "sidewalk", "silencer", "smartphone", "speakerphone",
    "spotlight", "stairwell", "standoff", "storyline", "subplot",
    "surveillance", "suspect", "suspense", "takedown", "text",
    "timestamp", "undercover", "viewfinder", "voiceover", "walkie",
    "talkie", "warehouse", "windshield", "wiretap",
    "okay", "yeah", "yep", "nah", "nope", "hey", "hmm", "uh", "um",
    "shh", "wow", "whoa", "ooh", "oops", "damn", "dammit", "hell",
    "gee", "geez", "huh", "psst", "yo", "alright", "wanna", "gonna",
    "gotta", "kinda", "sorta", "lemme", "gimme", "dunno",
    "upbeat", "uptight", "uptown", "upward", "upwards", "outskirts",
    "overboard", "overcome", "overflow", "overhear", "overlap",
    "overnight", "overseas", "overwhelm", "overwhelming",
    "afterward", "afterward", "altogether", "anywhere",
    "meantime", "meanwhile", "moreover", "nevertheless",
    "nonetheless", "notwithstanding", "otherwise", "therefore",
    "throughout", "whenever", "wherever", "whoever",
    "headphones", "screenshot", "textbook", "username", "password",
    "homepage", "database", "download", "upload", "upgrade",
    "feedback", "footprint", "framework", "guideline", "handbook",
    "headline", "heartbeat", "homework", "keyword", "landmark",
    "lifestyle", "makeup", "network", "newspaper", "notebook",
    "offspring", "outbreak", "outcome", "outline", "output",
    "outside", "overcome", "overlook", "overview", "partnership",
    "rainbow", "setback", "shortcut", "shutdown", "standpoint",
    "sunlight", "textbook", "trademark", "turnover", "update",
    "upgrade", "upset", "upstairs", "waterfall", "website",
    "weekend", "widespread", "wildlife", "withdraw", "workout",
    "workplace", "workshop", "worldwide",
    "ain't", "aren't", "can't", "couldn't", "didn't", "doesn't",
    "don't", "hadn't", "hasn't", "haven't", "he'd", "he'll", "he's",
    "here's", "how's", "i'd", "i'll", "i'm", "i've", "isn't",
    "it'd", "it'll", "it's", "let's", "mustn't", "she'd", "she'll",
    "she's", "shouldn't", "that's", "there's", "they'd", "they'll",
    "they're", "they've", "wasn't", "we'd", "we'll", "we're", "we've",
    "weren't", "what's", "when's", "where's", "who'd", "who'll",
    "who's", "won't", "wouldn't", "you'd", "you'll", "you're", "you've",
    "ma", "pa", "mama", "papa", "grandma", "grandpa",
    "abode", "ache", "afoot", "aglow", "alight", "amidst", "anew",
    "apiece", "asunder", "atone", "avow", "beckon", "befall", "begrudge",
    "behold", "bewail", "beware", "bewilder", "bicker", "blare",
    "bleach", "blemish", "bless", "blindfold", "blister", "blot",
    "blunder", "bogus", "bountiful", "brazen", "brim", "bristle",
    "broach", "brood", "buckle", "budge", "bulge", "bumble", "burden",
    "bustle", "bygone",
    "calamity", "caliber", "callous", "camouflage", "capsize",
    "cascade", "caulk", "cavern", "cease", "chafe", "chamber",
    "chant", "char", "cherish", "chide", "chime", "chisel", "churn",
    "cinder", "clad", "clamber", "clamor", "clamp", "clank", "clatter",
    "cleanse", "clench", "climax", "cling", "cloak", "clod", "clog",
    "clump", "clutch", "coax", "cobble", "coil", "commend", "commotion",
    "compel", "comply", "conceal", "concede", "condemn", "condone",
    "confide", "confiscate", "congregate", "connive", "console",
    "conspire", "constrain", "constrict", "contemplate", "contort",
    "convene", "converge", "converse", "convey", "convict", "cope",
    "corrode", "covet", "crackle", "cradle", "cramp", "crane",
    "crave", "creak", "crease", "creed", "creep", "crescent",
    "crest", "cringe", "crinkle", "crisp", "crouch", "crow",
    "crumble", "crumple", "crusade", "cuddle", "cuff", "culminate",
    "curb", "curd", "curl",
    "dabble", "dagger", "dainty", "dale", "dampen", "dangle",
    "dapper", "daunt", "dawdle", "daze", "dazzle", "debris",
    "deceased", "deceit", "deceive", "decree", "deduce", "defile",
    "defy", "deluge", "demolish", "demure", "denounce", "deplore",
    "deploy", "deprive", "deride", "descend", "desecrate",
    "despise", "destitute", "detain", "deter", "detest", "detonate",
    "deviate", "devious", "devour", "dew", "dexterity", "dilapidated",
    "din", "dingy", "dirge", "discard", "discern", "disdain",
    "disfigure", "disgruntled", "dismal", "dismantle", "dismay",
    "dispel", "disperse", "disrupt", "dissent", "distill", "divert",
    "divulge", "docile", "dodge", "doleful", "dormant", "dote",
    "doze", "drape", "drastic", "drawl", "dread", "dreary", "drench",
    "drizzle", "drool", "droop", "drove", "drowsy", "drudge",
    "dubious", "duel", "dug", "dusk", "dwell", "dwindle",
    "eavesdrop", "ebb", "eccentric", "eclipse", "edifice",
    "eerie", "efface", "elaborate", "elapse", "elated", "elope",
    "elude", "emaciated", "embark", "embed", "emblem", "embody",
    "embroil", "emerge", "emit", "emphatically", "enact", "enchant",
    "encircle", "enclose", "encompass", "endeavor", "endow",
    "engrave", "engross", "engulf", "enigma", "enmity", "ensue",
    "entail", "entangle", "enthrall", "entice", "entreat", "envision",
    "epoch", "equate", "erode", "errand", "estrange", "etch",
    "evade", "evict", "exalt", "excavate", "exclaim", "exempt",
    "exert", "exhale", "exhilarate", "expanse", "expel", "expire",
    "exploit", "extol", "extract", "exude", "exult",
    "fable", "fabricate", "facet", "falter", "famish", "farce",
    "fathom", "fatigue", "fawn", "feat", "feeble", "feign", "feint",
    "felon", "fend", "ferment", "ferocious", "fervent", "fester",
    "fetid", "fetter", "feud", "fiasco", "fickle", "fidget",
    "filth", "finesse", "flair", "flank", "flare", "flaunt", "flaw",
    "fledgling", "fleece", "flimsy", "flinch", "flit", "flog",
    "flounder", "flourish", "flout", "fluctuate", "fluke", "flurry",
    "flutter", "fodder", "foliage", "folly", "forage", "forbearance",
    "foreboding", "forge", "forlorn", "forsake", "forte", "forthright",
    "foul", "fracas", "frail", "fray", "frenzy", "fret",
    "frivolous", "frolic", "frugal", "fumble", "fume", "furrow",
    "furtive", "fuselage", "futile", "fuzzy",
    "gag", "gait", "gallivant", "gamble", "garble", "garnish",
    "gaunt", "gawk", "ghastly", "gibberish", "giddy", "glaze",
    "glee", "glide", "glimmer", "gloat", "gnaw", "gouge", "grapple",
    "gratitude", "gravel", "grime", "grimace", "gripe", "grope",
    "grovel", "grudge", "grueling", "gruesome", "gruff", "grumble",
    "grunt", "guise", "gulp", "gurgle", "gush", "gust", "gutter",
    "hack", "hail", "hallmark", "hamper", "hapless", "harass",
    "hardened", "hassle", "hasten", "hatchet", "haunt", "havoc",
    "haze", "hazy", "heed", "hefty", "helm", "herald",
    "heresy", "hermit", "hew", "hideout", "hinder", "hinge",
    "hoarse", "hoax", "hobble", "hoist", "homage", "hone",
    "hopper", "horde", "hover", "howl", "huddle", "hue",
    "hulk", "humble", "hump", "hunch", "hurtle", "hustle",
    "hymn",
    "idyllic", "ignite", "imbue", "immerse", "imminent",
    "impasse", "impede", "imperative", "impervious", "implore",
    "imposing", "impound", "impromptu", "improvise", "impudent",
    "incite", "incoherent", "indifferent", "indignant", "indulge",
    "inept", "inert", "infamous", "infatuate", "inflame", "inflict",
    "inhabit", "inhale", "insatiable", "inscribe", "insinuate",
    "insipid", "install", "instigate", "instill", "intermittent",
    "intimidate", "intricate", "intrude", "inundate", "invoke",
    "irate", "irksome",
    "jabber", "jade", "jag", "jamb", "jangle", "jaunt", "jeer",
    "jeopardize", "jest", "jilt", "jingle", "jostle", "jovial",
    "jubilant", "jumble", "junction", "jut",
    "keen", "kindle", "kinship", "knack",
    "lament", "languid", "languish", "lank", "lapse", "lash",
    "latch", "lavender", "lax", "ledge", "leer", "lethal",
    "liable", "libel", "lilt", "limelight", "limp", "linger",
    "listless", "litany", "lithe", "loathe", "lofty", "loom",
    "loot", "lopsided", "lucid", "lug", "lugubrious", "lukewarm",
    "lumber", "luminous", "lunge", "lurch", "lurid", "lurk",
    "luster", "lustre",
    "maim", "makeshift", "malice", "mangle", "mantle", "mar",
    "maraud", "mare", "marvel", "mash", "masquerade", "mast",
    "maul", "meager", "meddle", "meek", "mellow", "memoir",
    "menace", "mend", "merc", "mesmerize", "mingle", "minuscule",
    "mire", "mirth", "mischief", "mishap", "mock", "molten",
    "momentous", "morale", "morsel", "mortar", "mosey", "motley",
    "mourn", "muddle", "muffle", "mumble", "mundane", "murky",
    "muse", "muster", "mutilate", "mutter", "muzzle",
    "nab", "nag", "naive", "nape", "nestle", "nettle", "nimble",
    "nocturnal", "nomad", "nonchalant", "nook", "notch",
    "nudge", "nullify", "numb",
    "oaf", "oblique", "oblivion", "oblivious", "obnoxious",
    "obscure", "obsolete", "ominous", "onslaught", "opaque",
    "ordain", "ornate", "ostracize", "oust", "outcry",
    "outlandish", "outlaw", "outright", "outskirt", "outweigh",
    "overdue", "overhaul",
    "padlock", "pall", "pallid", "palpable", "pamper", "pandemonium",
    "pang", "pant", "parable", "parole", "parsimony", "pastime",
    "pauper", "peal", "pebble", "peep", "pelt", "penance",
    "pensive", "peril", "perish", "perk", "permeate", "perpetuate",
    "perplex", "persecute", "pertain", "perturb", "pervade",
    "pesky", "pester", "pickle", "pilfer", "pillage", "pinch",
    "pinnacle", "pique", "placate", "placid", "plague", "plank",
    "plaster", "plateau", "plead", "plight", "plod", "plop",
    "pluck", "plummet", "plunder", "plunk", "poach", "poke",
    "ponder", "pore", "potent", "pounce", "pout", "prance",
    "prattle", "preen", "premise", "prestige", "prick",
    "prod", "prodigal", "profane", "prolong", "prop",
    "propel", "prowl", "prude", "pry", "pucker", "pummel",
    "pun", "punctual", "pungent", "puny", "purge", "putter",
    "quaint", "qualm", "quandary", "quarrel", "quarry",
    "quell", "quench", "quibble", "quiver", "quirky",
    "rafter", "ragged", "ramble", "rampant", "ransack",
    "rant", "rap", "rascal", "rash", "rasp", "rattle",
    "ravage", "rave", "ravenous", "ravine", "recede",
    "reckless", "reckon", "recoil", "reek", "refrain",
    "relish", "reminisce", "remorse", "repel", "repent",
    "replenish", "reprimand", "reproach", "reprieve", "repulse",
    "resent", "residue", "resign", "resilient", "retaliate",
    "retort", "revel", "revere", "revoke", "riddle",
    "riffle", "rigmarole", "rile", "riveting", "roam",
    "robust", "rogue", "roost", "rowdy", "rubble",
    "ruckus", "ruffle", "rumble", "rummage", "rump",
    "rupture", "rustic", "rustle", "rut",
    "sabotage", "sag", "salvage", "sanctuary", "sane",
    "sap", "sardonic", "sash", "saturate", "saunter",
    "savage", "savor", "savvy", "scald", "scamper",
    "scathe", "scavenge", "scoff", "scold", "scoot",
    "scorch", "scoundrel", "scour", "scowl", "scram",
    "scrub", "scrutinize", "scuffle", "scurry", "seethe",
    "serene", "sever", "shabby", "shackle", "shatter",
    "sheepish", "shimmer", "shirk", "shiver", "shove",
    "shrewd", "shriek", "shrivel", "shroud", "shudder",
    "shuffle", "shun", "sift", "simmer", "sinister",
    "skid", "skim", "skimp", "skirmish", "skulk",
    "slack", "slag", "slant", "slate", "slay",
    "sleek", "slick", "sling", "slink", "slither",
    "slob", "slog", "slosh", "slouch", "slug",
    "slur", "smack", "smear", "smirk", "smother",
    "smudge", "smug", "snag", "snarl", "snare",
    "sneer", "snicker", "snide", "sniff", "snitch",
    "snoop", "snore", "snort", "snout", "snub",
    "snuff", "snuggle", "solemn", "somber", "soothe",
    "soprano", "sordid", "sovereign", "spade", "sparse",
    "spasm", "spawn", "speck", "spew", "splatter",
    "splinter", "splurge", "spoil", "spook", "spur",
    "spurn", "sputter", "squab", "squall", "squander",
    "squat", "squawk", "squeak", "squeal", "squint",
    "squirm", "stagger", "stagnant", "stake", "stale",
    "stammer", "stampede", "standstill", "staple", "stark",
    "startle", "stash", "statute", "staunch", "stave",
    "stead", "stealth", "stench", "stern", "stew",
    "stifle", "stigma", "stilted", "stint", "stipulate",
    "stockpile", "stoic", "stomp", "stoop", "strangle",
    "strap", "strewn", "stride", "strife", "stringent",
    "strive", "strut", "stub", "stumble", "stump",
    "stun", "stupor", "subdue", "sublime", "submerge",
    "subordinate", "subside", "subtle", "succumb", "sulk",
    "sullen", "summit", "summon", "supple", "suppress",
    "surge", "surmise", "surpass", "surplus", "swagger",
    "swarm", "sway", "swerve", "swirl", "swoop",
    "synopsis",
    "taint", "tamper", "tangle", "tantalize", "taunt",
    "taut", "tedious", "teem", "temper", "tempo",
    "tenant", "tenacious", "tendon", "tense", "tepid",
    "terrain", "terse", "thaw", "thicket", "thorny",
    "thrash", "thresh", "throb", "throttle", "thud",
    "thwart", "tilt", "tinge", "tinker", "tint",
    "tirade", "toil", "topple", "torment", "torrent",
    "totter", "tout", "tow", "toxic", "trample",
    "tranquil", "tread", "tremor", "trespass", "trifle",
    "trudge", "truant", "tumult", "turbulent", "turmoil",
    "tusk", "tutor", "twang", "twig", "twirl",
    "twitch",
    "ulterior", "unanimous", "uncanny", "undercut",
    "underscore", "unearth", "unfurl", "unkempt",
    "unravel", "unscrupulous", "unsightly", "upbraid",
    "upheaval", "uphold", "uproot", "uproar", "usher",
    "usurp", "utmost", "utterance",
    "vagrant", "valiant", "valor", "vandal", "vanguard",
    "vanquish", "vault", "veer", "vehement", "vendetta",
    "vengeance", "vent", "venomous", "venture", "veranda",
    "verge", "vernacular", "vex", "vigilant", "vindicate",
    "vindictive", "vow",
    "wad", "waddle", "wail", "waive", "wane",
    "warden", "warped", "wary", "waylay", "weary",
    "wedge", "whack", "whelp", "whiff", "whim",
    "whimper", "whine", "whirl", "whisk", "whittle",
    "wield", "wilt", "wily", "wince", "winch",
    "wistful", "wither", "wobble", "woe", "wrangle",
    "wrath", "wreak", "wren", "wrench", "wrestle",
    "wretched", "wring", "writhe",
    "yearn", "yelp",
    "zany", "zap", "zenith", "zephyr", "zilch", "zinc", "zing", "zip",
    # Commonly missed short words
    "if", "is",
    # Common inflected forms: plurals, verb conjugations, participles
    "am", "asks", "asked", "asking", "begins", "boys", "brings",
    "bringing", "brothers", "calls", "called", "calling", "cars", "cats",
    "closes", "comes", "coming", "cuts", "cutting", "daughters", "days",
    "dogs", "doors", "drops", "dropped", "dropping", "eyes", "falls",
    "falling", "fathers", "feels", "feeling", "finds", "friends", "gets",
    "getting", "gives", "giving", "girls", "goes", "going", "guns", "guys",
    "hands", "helps", "helped", "helping", "hits", "hitting", "holds",
    "holding", "houses", "keeps", "keeping", "kids", "kills", "killed",
    "killing", "knows", "knowing", "lets", "letting", "lives", "lived",
    "living", "looks", "looked", "looking", "makes", "making", "mothers",
    "moves", "moved", "moving", "myself", "nights", "opens", "opened",
    "opening", "parents", "passes", "passed", "passing", "pays", "paying",
    "phones", "picks", "picked", "picking", "places", "plays", "played",
    "playing", "pulls", "pulled", "pulling", "pushes", "pushed", "pushing",
    "puts", "putting", "raises", "raised", "raising", "reads", "reading",
    "rooms", "runs", "running", "says", "saying", "seems", "seeming",
    "sets", "setting", "shows", "showed", "showing", "sisters", "sits",
    "sitting", "sons", "stands", "standing", "starts", "started",
    "starting", "stops", "stopped", "stopping", "streets", "takes",
    "taking", "tells", "telling", "things", "thinks", "thinking", "times",
    "tries", "tried", "trying", "turns", "turned", "turning", "walks",
    "walked", "walking", "wants", "wanting", "ways", "words", "works",
    "worked", "working", "writes", "writing", "years",
    # More common verb forms
    "acts", "acted", "acting", "adds", "added", "adding", "agrees",
    "agreed", "agreeing", "allows", "allowed", "allowing", "appears",
    "appeared", "appearing", "believes", "believed", "believing",
    "breaks", "broke", "breaking", "builds", "built", "building",
    "buys", "bought", "buying", "carries", "carried", "carrying",
    "catches", "catching", "changes", "changed", "changing", "checks",
    "checked", "checking", "chooses", "chose", "choosing", "claims",
    "claimed", "claiming", "clears", "cleared", "clearing", "climbs",
    "climbed", "climbing", "closes", "closed", "closing", "continues",
    "continued", "continuing", "controls", "controlled", "controlling",
    "counts", "counted", "counting", "covers", "covered", "covering",
    "creates", "created", "creating", "crosses", "crossed", "crossing",
    "cries", "cried", "crying", "decides", "decided", "deciding",
    "describes", "described", "describing", "dies", "died", "dying",
    "discovers", "discovered", "discovering", "does", "draws", "drew",
    "drawing", "drinks", "drank", "drinking", "drives", "drove",
    "driving", "eats", "eaten", "eating", "ends", "ended", "ending",
    "enters", "entered", "entering", "explains", "explained",
    "explaining", "faces", "faced", "facing", "falls", "fell",
    "filling", "flies", "flew", "flying", "follows", "followed",
    "following", "forces", "forced", "forcing", "forgets", "forgot",
    "forgetting", "forms", "formed", "forming", "gains", "gained",
    "gaining", "grows", "grew", "growing", "happens", "happened",
    "happening", "heads", "headed", "heading", "hears", "hearing",
    "hurts", "hurting", "includes", "included", "including",
    "increases", "increased", "increasing", "joins", "joined",
    "joining", "jumps", "jumped", "jumping", "lays", "laid", "laying",
    "leads", "leading", "learns", "learned", "learning", "leaves",
    "leaving", "lies", "lied", "lying", "lifts", "lifted", "lifting",
    "listens", "listened", "listening", "loses", "losing", "loves",
    "loved", "loving", "marks", "marked", "marking", "matters",
    "mattered", "mattering", "means", "meaning", "meets", "meeting",
    "minds", "minded", "minding", "misses", "missed", "missing",
    "moves", "named", "naming", "needs", "needed", "needing", "notes",
    "noted", "noting", "notices", "noticed", "noticing", "offers",
    "offered", "offering", "orders", "ordered", "ordering", "owns",
    "owned", "owning", "pauses", "paused", "pausing", "points",
    "pointed", "pointing", "presses", "pressed", "pressing", "produces",
    "produced", "producing", "provides", "provided", "providing",
    "reaches", "reached", "reaching", "realizes", "realized",
    "realizing", "receives", "received", "receiving", "recognizes",
    "recognized", "recognizing", "remains", "remained", "remaining",
    "remembers", "remembered", "remembering", "removes", "removed",
    "removing", "replies", "replied", "replying", "reports", "reported",
    "reporting", "requires", "required", "requiring", "returns",
    "returned", "returning", "rides", "rode", "riding", "rings",
    "rang", "ringing", "rises", "rising", "rolls", "rolled", "rolling",
    "saves", "saved", "saving", "sees", "seeing", "seeks", "seeking",
    "sells", "sold", "selling", "sends", "sent", "sending", "serves",
    "served", "serving", "shares", "shared", "sharing", "shoots",
    "shot", "shooting", "shouts", "shouted", "shouting", "signs",
    "signed", "signing", "sings", "sang", "singing", "slides", "slid",
    "sliding", "smiles", "smiled", "smiling", "speaks", "spoke",
    "speaking", "spends", "spent", "spending", "steps", "stepped",
    "stepping", "stares", "stared", "staring", "states", "stated",
    "stating", "stays", "stayed", "staying", "strikes", "struck",
    "striking", "studies", "studied", "studying", "suggests",
    "suggested", "suggesting", "supports", "supported", "supporting",
    "talks", "talked", "talking", "teaches", "taught", "teaching",
    "throws", "threw", "throwing", "touches", "touched", "touching",
    "travels", "traveled", "travelling", "waits", "waited", "waiting",
    "watches", "watched", "watching", "wears", "wore", "wearing",
    "wins", "winning", "wishes", "wished", "wishing", "wonders",
    "wondered", "wondering",
    # Common noun plurals
    "arms", "babies", "backs", "bags", "balls", "banks", "bars",
    "beds", "bills", "birds", "bits", "blocks", "boats", "bodies",
    "bombs", "bones", "books", "boots", "boxes", "brains", "bridges",
    "buildings", "buses", "cards", "cases", "cells", "chairs",
    "chances", "characters", "children", "choices", "churches",
    "cities", "classes", "clothes", "clouds", "clubs", "colors",
    "colours", "companies", "computers", "conditions", "cops",
    "corners", "costs", "countries", "courts", "cups", "deaths",
    "decisions", "details", "differences", "doctors", "dollars",
    "dreams", "drugs", "ears", "edges", "effects", "efforts",
    "elements", "enemies", "events", "examples", "experiences",
    "faces", "facts", "families", "farms", "fears", "feelings",
    "feet", "fields", "figures", "films", "fingers", "fires",
    "floors", "flowers", "forces", "forms", "games", "gardens",
    "gates", "governments", "groups", "guards", "heads", "hearts",
    "hills", "holes", "homes", "horses", "hospitals", "hotels",
    "hours", "ideas", "images", "interests", "islands", "issues",
    "jobs", "keys", "kings", "knees", "lands", "laws", "leaders",
    "leaves", "legs", "letters", "levels", "lights", "lines", "lips",
    "lists", "lots", "machines", "maps", "marks", "matters",
    "meals", "members", "memories", "messages", "methods", "miles",
    "minutes", "models", "moments", "months", "mountains", "mouths",
    "movies", "muscles", "names", "nations", "necks", "needs",
    "nerves", "notes", "numbers", "objects", "offices", "officers",
    "ones", "operations", "orders", "pages", "papers", "parts",
    "parties", "paths", "patients", "patterns", "pictures", "pieces",
    "plans", "plants", "players", "points", "policies", "positions",
    "pounds", "powers", "prices", "problems", "products", "programs",
    "programmes", "projects", "questions", "races", "records",
    "regions", "relations", "reports", "results", "rights", "rivers",
    "roads", "rocks", "roles", "rules", "schools", "seats",
    "seconds", "sections", "services", "shapes", "ships", "shoes",
    "shops", "shots", "shoulders", "sides", "signs", "sites",
    "situations", "skills", "soldiers", "songs", "sorts", "sounds",
    "sources", "spaces", "spirits", "sports", "stages", "stairs",
    "stars", "states", "stations", "steps", "stones", "stories",
    "students", "subjects", "systems", "tables", "teams", "tears",
    "teeth", "terms", "tests", "thoughts", "towns", "tracks",
    "trees", "troops", "types", "units", "values", "views",
    "voices", "walls", "wars", "waters", "weapons", "weeks",
    "windows", "wings", "wives", "women", "woods",
    # Common adjective/adverb forms
    "bigger", "biggest", "smaller", "smallest", "older", "oldest",
    "younger", "youngest", "longer", "longest", "shorter", "shortest",
    "higher", "highest", "lower", "lowest", "larger", "largest",
    "faster", "fastest", "slower", "slowest", "harder", "hardest",
    "softer", "softest", "louder", "loudest", "quieter", "quietest",
    "taller", "tallest", "wider", "widest", "deeper", "deepest",
    "thicker", "thickest", "thinner", "thinnest", "heavier",
    "heaviest", "lighter", "lightest", "darker", "darkest",
    "brighter", "brightest", "warmer", "warmest", "cooler", "coolest",
    "cleaner", "cleanest", "nicer", "nicest", "easier", "easiest",
    "happier", "happiest", "sadder", "saddest", "angrier", "angriest",
    "prettier", "prettiest", "uglier", "ugliest",
})

_ALPHABET = "abcdefghijklmnopqrstuvwxyz"

_SCENE_HEADING_RE = re.compile(
    r"^\s*(?:INT\.|EXT\.|INT\./EXT\.|I/E\.)\s",
    re.IGNORECASE,
)
_NOTE_RE = re.compile(r"\[\[.*?\]\]", re.DOTALL)
_FORCED_CHARACTER_RE = re.compile(r"^@\s*(.+)$", re.MULTILINE)
_WORD_RE = re.compile(r"[a-zA-Z''’]+")
_HAS_DIGIT_RE = re.compile(r"\d")
_ALL_CAPS_WORD_RE = re.compile(r"^[A-Z''’]+$")
_ALL_CAPS_LINE_RE = re.compile(r"^[A-Z''’ .\-]+$")


@dataclass
class SpellIssue:
    word: str
    line: int
    column: int
    suggestions: list[str]
    context: str


class SpellChecker:
    def __init__(self) -> None:
        self._dictionary: set[str] = set(_COMMON_WORDS)
        self._custom_words: set[str] = set()
        self._skip_patterns: list[re.Pattern] = [
            _SCENE_HEADING_RE,
            _NOTE_RE,
            _FORCED_CHARACTER_RE,
        ]

    def add_word(self, word: str) -> None:
        self._custom_words.add(word.lower())

    def add_words(self, words: list[str]) -> None:
        for w in words:
            self._custom_words.add(w.lower())

    def remove_word(self, word: str) -> None:
        self._custom_words.discard(word.lower())

    def load_custom_words(self, path: str) -> None:
        p = Path(path)
        if not p.exists():
            return
        for raw_line in p.read_text(encoding="utf-8").splitlines():
            w = raw_line.strip()
            if w:
                self._custom_words.add(w.lower())

    def save_custom_words(self, path: str) -> None:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(
            "\n".join(sorted(self._custom_words)) + "\n",
            encoding="utf-8",
        )

    def check_word(self, word: str) -> bool:
        low = word.lower()
        return low in self._dictionary or low in self._custom_words

    def suggest(self, word: str, max_suggestions: int = 5) -> list[str]:
        low = word.lower()
        known = self._dictionary | self._custom_words
        candidates = _edits1(low) & known
        if not candidates:
            candidates = {
                e2 for e1 in _edits1(low) for e2 in _edits1(e1)
            } & known
        return sorted(candidates)[:max_suggestions]

    def extract_script_names(self, content: str) -> set[str]:
        names: set[str] = set()
        for raw_line in content.splitlines():
            stripped = raw_line.strip()
            if _SCENE_HEADING_RE.match(stripped):
                heading_body = re.sub(
                    r"^\s*(?:INT\.|EXT\.|INT\./EXT\.|I/E\.)\s*",
                    "",
                    stripped,
                    flags=re.IGNORECASE,
                )
                for token in re.split(r"[\s/\-–—,.()]+", heading_body):
                    if token and not _HAS_DIGIT_RE.search(token):
                        names.add(token.lower())

            if stripped.startswith("@"):
                forced = stripped[1:].strip()
                for token in forced.split():
                    names.add(token.lower())

            if _ALL_CAPS_LINE_RE.match(stripped) and len(stripped) > 1:
                for token in stripped.split():
                    names.add(token.lower())

        return names

    def check_text(self, content: str) -> list[SpellIssue]:
        auto_names = self.extract_script_names(content)
        note_spans: list[tuple[int, int]] = []
        for m in _NOTE_RE.finditer(content):
            note_spans.append((m.start(), m.end()))

        lines = content.split("\n")
        issues: list[SpellIssue] = []
        offset = 0

        for line_no, raw_line in enumerate(lines):
            stripped = raw_line.strip()

            if _SCENE_HEADING_RE.match(stripped):
                offset += len(raw_line) + 1
                continue

            if stripped.startswith("@"):
                offset += len(raw_line) + 1
                continue

            for m in _WORD_RE.finditer(raw_line):
                word = m.group()
                col = m.start()
                abs_start = offset + col

                if _in_note_span(abs_start, note_spans):
                    continue

                if len(word) <= 1:
                    continue

                if _ALL_CAPS_WORD_RE.match(word):
                    continue

                if _HAS_DIGIT_RE.search(word):
                    continue

                low = word.lower()
                parts = re.split(r"['’]", low)
                all_known = all(
                    (not p) or p in self._dictionary or p in self._custom_words or p in auto_names
                    for p in parts
                )
                if all_known:
                    continue

                if low in auto_names:
                    continue

                sug = self.suggest(word)
                issues.append(SpellIssue(
                    word=word,
                    line=line_no,
                    column=col,
                    suggestions=sug,
                    context=raw_line,
                ))

            offset += len(raw_line) + 1

        return issues


def _in_note_span(pos: int, spans: list[tuple[int, int]]) -> bool:
    for start, end in spans:
        if start <= pos < end:
            return True
    return False


def _edits1(word: str) -> set[str]:
    splits = [(word[:i], word[i:]) for i in range(len(word) + 1)]
    deletes = {a + b[1:] for a, b in splits if b}
    transposes = {a + b[1] + b[0] + b[2:] for a, b in splits if len(b) > 1}
    replaces = {a + c + b[1:] for a, b in splits if b for c in _ALPHABET}
    inserts = {a + c + b for a, b in splits for c in _ALPHABET}
    return deletes | transposes | replaces | inserts
